version: '3'

services:

  db:
    image: postgres:15-bullseye
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgresql:
